### ISSUE TITLE
Unable to open requestedHTML document.

### ISSUE THREAD

**Issue by ghost** [butcherg/rawproc#23]
When using  _Help -> View Help..._ the help window opens and also an error message that reads:

```
Rawproc error
Unable to open requested HTML document: file:///home/jade/.local/bin/rawprocdoc.zip#zip:main.html
OK
```

After clicking _OK_ I do have full access to all the tabs in help.

My own little investigation showed this:

If I manually unzip the file and look for main.html I find one reference  in index.html (at the bottom), but there is no main.html present.

**Comment by butcherg** [comment]
Ah, left out a step in "Other Tasks" in the README.  Need to run 'make docpages', then run 'make doc' to extract all the tagged comments from the source for inclusion in the help file.  main.html has the version number inserted during make docpages...

Just committed a README.md change to include this.
