### ISSUE TITLE
Please make a new release with CMake support

### ISSUE THREAD

**Issue by barracuda156** [butcherg/rawproc#27]
The last tag, 1.3, does not have CMake support yet. Could you please make a new minor or micro release?

**Comment by butcherg** [comment]
Yeah, probably about time...

Will take a bit, need to clean up some stuff and make documentation for the new things.

**Comment by barracuda156** [comment]
@butcherg Could you please take a look at clang build errors?

**Comment by butcherg** [comment]
Yep, see #d387f38

**Comment by butcherg** [comment]
Done, version 1.4.0
